### PR TITLE
Use babel jsxPragma option.

### PR DESCRIPTION
**Pull request by KenPowers**
Using Babel's `jsxPragma` option reduces duplication and makes changes like 72a599df70b09b0e2177c2c7e87e32c7c5a6ffdb easier.

### CODE REVIEW

**Comment by garbles** [comment]
Wow fantastic! Thanks! :tada: 

If you move the config to the [.babelrc](https://github.com/BrewhouseTeam/yolk-todomvc/blob/master/.babelrc) file, I will merge this in ASAP.

**Comment by KenPowers** [comment]
Wow, I completely missed that that file already existed.

In any case, there you have it.

**Comment by garbles** [comment]
@KenPowers if you're up for it, feel free to add a note in the [Using JSX](https://github.com/BrewhouseTeam/yolk#using-jsx) section of the yolk repo README.

**Comment by KenPowers** [comment]
Will do.

**Pull request merged**
